### ISSUE TITLE
Exclude for a stream?

### ISSUE THREAD

**Issue by Lailend** [villadora/express-bunyan-logger#20]
Hey I was wondering if it is possible to specify specific excluding for streams.

Since the req and res object can get pretty big I dont love to exclude them in the console. But I would like to keep them stored in a file or database.

Thnx.

**Comment by villadora** [comment]
Hi, sorry to say that won't be in this lib. What's this lib do is logging express information and pass it to bunyan.

I think in your situation a object stream which can play as a filter and than pipe different content into different stream is a better way. and that is a more generic lib. It could works prefect with bunyan itself and in many other situation.

But I doesn't find one in npm by myself, maybe you can build a package do this:-)
