### ISSUE TITLE
`process.hrtime()` vs `Date.now()`?

### ISSUE THREAD

**Issue by ruffrey** [villadora/express-bunyan-logger#21]
I am interested in this feature for very high performance APIs. Any thoughts appreciated.

**Comment by villadora** [comment]
I agree. For backward compatibility, 'response-time' is kept, and new field called 'response-hrtime' is added.

**Comment by villadora** [comment]
resolved in eeada754df92aa2a1af777da7d3a838951260f4d

**Comment by ruffrey** [comment]
:+1: THANKS
