### ISSUE TITLE
Add support to use the already configured bunyan logger instance

### ISSUE THREAD

**Issue by bytekoders** [villadora/express-bunyan-logger#22]
The current module forces to create a different bunyan logger instance for express which I think is not very helpful if you have a bunyan logger instance in your app.

**Comment by PaulMougel** [comment]
Looks like it is already possible, see https://github.com/villadora/express-bunyan-logger/issues/14#issuecomment-51422730

**Comment by bytekoders** [comment]
Thanks @PaulMougel.. guess I didn't go through the stuff with enough granularity
