### ISSUE TITLE
Can't install with iojs 3

### ISSUE THREAD

**Issue by MCF** [villadora/express-bunyan-logger#29]
Attempting to installing with iojs 3.3 results in the following error:

```
$ npm install express-bunyan-logger
> dtrace-provider@0.5.0 install /Users/mike/code/proj/node_modules/express-bunyan-logger/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------
express-bunyan-logger@1.1.1 node_modules/express-bunyan-logger
├── useragent@2.1.7 (lru-cache@2.2.4)
└── bunyan@1.4.0 (safe-json-stringify@1.0.3, mv@2.1.1, dtrace-provider@0.5.0)
```
The root cause seems to be that node-bunyan (aka bunyan) has a stale dependency on node-dtrace 0.5 which is incompatible with iojs 3.  There is already a pull request to fix the problem in node-bunyan:

https://github.com/trentm/node-bunyan/pull/294

I'm sure everything will be fixed up over the next few days/weeks.  In the meantime, if you must install express-bunyan-logger with iojs 3 I have a forked repo that depends on a node-bunyan fork that has the dtrace fix applied:

https://github.com/MCF/express-bunyan-logger

Add the following line in your package.json to (temporarily) get the install working:

```
"express-bunyan-logger": "MCF/express-bunyan-logger",
```

Be sure to switch back to the normal package once the dependency problem in bunyan has been fixed and released.

**Comment by villadora** [comment]
sorry for having no  spare time to maintain this lib to keep catch. A merge request, or some one want to take maitaining is welcome :-)
