### ISSUE TITLE
includesFn in doc but not there

### ISSUE THREAD

**Issue by YouriT** [villadora/express-bunyan-logger#33]
Well I think the title is pretty much explanatory.

Is there any particular reason about that?

**Comment by ttshaw** [comment]
Really want to see includesFn goes to npm registry too.

Like this module, please keep updating.

**Comment by marcbachmann** [comment]
Nobody did a release to npm. I just published v1.2.0

**Comment by marcbachmann** [comment]
Please report back whether everything is working.

**Comment by ttshaw** [comment]
Just tested it and it works very well. Thanks very much!

**Comment by marcbachmann** [comment]
You're welcome

**Comment by YouriT** [comment]
Yep it works! Thanks a lot! I can finally remove my workaround :D Sorry for the delay...
